Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Lint/AssignmentInCondition:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AndOr:
  EnforcedStyle: conditionals

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/Documentation:
  Enabled: false
